# Homebrew
export HOMEBREW_NO_EMOJI=1

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

if [ -d ~/.function ]; then
    for func in ~/.function/*
    do 
        . $func
    done
fi


# Zsh Plugins
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# Go 
export GO111MODULE=on
export GOPROXY="https://goproxy.cn,direct"
export GOPRIVATE="*.sensetime.com"



# System variables
export KUBECONFIG=/Users/luhaojing/.kube/config-133

# Prompt
PROMPT='%F{yellow}%1~ %#%f '
RPROMPT='[%F{yellow}%?%f]'

# Switch between clusters 
c133() {
    unset KUBECONFIG
    export KUBECONFIG=/Users/luhaojing/.kube/config-133
}

c94() {
    unset KUBECONFIG
    export KUBECONFIG=/Users/luhaojing/.kube/config-94
}
